pool:
  vmImage: ubuntu-latest

trigger: 
- main

stages:
- stage: Build
  displayName: Publish Lambdas
  jobs:
  - job: PublishAdvisor
    displayName: Publish Advisor
    steps:
    - task: UseDotNet@2
      inputs:
        version: '6.x'
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        workingDirectory: '$(Build.SourcesDirectory)/src/Scion.Lambda.Advisor/src/Scion.Lambda.Advisor'
        arguments: '--configuration Release -p:PublishReadyToRun=true --output $(Build.ArtifactStagingDirectory)/Scion.Lambda.Advisor'
        zipAfterPublish: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Scion.Lambda.Advisor'
        ArtifactName: 'Scion.Lambda.Advisor'