pool:
  vmImage: ubuntu-latest

trigger: 
- main

stages:
- stage: Build
  displayName: Publish Lambdas
  jobs:
  - job: PublishAdvisor
    displayName: Publish Advisor
    steps:
    - task: UseDotNet@2
      inputs:
        version: '6.x'
    - task: LambdaNETCoreDeploy@1
      inputs:
        awsCredentials: 'AWS User'
        regionName: 'ap-southeast-2'
        command: 'deployFunction'
        packageOnly: true
        packageOutputFile: '$(Build.ArtifactStagingDirectory)/Scion.Lambda.Advisor.zip'
        lambdaProjectPath: '$(Build.SourcesDirectory)/src/Scion.Lambda.Advisor/src/Scion.Lambda.Advisor'
        functionName: ''
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/Scion.Lambda.Advisor.zip'
        ArtifactName: 'Scion.Lambda.Advisor'
