pool:
  vmImage: ubuntu-latest

trigger: 
- main

stages:
- stage: Build
  displayName: Build Lambdas
  jobs:
  - job: PublishLambdas
    displayName: Publish Lambdas
    steps:
    - task: UseDotNet@2
      inputs:
        version: '6.x'
    - task: DotNetCoreCLI@2
      displayName: Publish Advisor
      inputs:
        command: publish
        publishWebProjects: false
        workingDirectory: '$(Build.SourcesDirectory)/src/Scion.Lambda.Advisor'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true